/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package asma_proj1;

import jade.core.Profile;
import jade.core.ProfileImpl;
import jade.core.Runtime;
import jade.wrapper.AgentController;
import jade.wrapper.ContainerController;
import jade.wrapper.StaleProxyException;

public class App {
    public static void main(String[] args) {
        Runtime runtime = Runtime.instance();
        Profile profile = new ProfileImpl();
        
        ContainerController mainContainer = runtime.createMainContainer(profile);

        try {
            AgentController rma = mainContainer.createNewAgent("rma", "jade.tools.rma.rma", null);
            rma.start();
        }
        catch (StaleProxyException e) {
            e.printStackTrace();
        }
    }
}
